sudo: false
dist: trusty

matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd backend/tests
      script:
        - python -m unittest discover

    - language: node_js
      node_js: 10
      before_script:
        - cd android/AppName
      script:
        - ./gradlew build connectedCheck
