sudo: false
dist: trusty

matrix:
  include:
    - language: python
      python: 3.7-dev
      install:
        - pip install -r .\config\requirements.txt
      script:
        - pytest .\config\test_.py

    - language: node_js
      node_js: 10
      script:
        - jest