name: Release SDK
on:
  push:
    branches:
      - master
    # tags:
    #   - v*
jobs:
  build:
    name: Generate Win-x64 Release for Next
    runs-on: windows-latest
    steps:
      - name: Checkout Core
        uses: actions/checkout@v2
      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          repository: "miswanting/Era.js-SDK"
          path: ../Era.js-SDK
      - name: Dir INFO
        run: dir
      - name: Dir Parent INFO
        run: |
          cd ..
          dir
